### ISSUE TITLE
Questions about   torch_cluster\__init__.py  

### ISSUE THREAD

**Issue by Max-Well-Wang** [justanhduc/brushstroke-parameterized-style-transfer#4]
Hello, I installed torch_cluster according to your requirements, but in torch_cluster, but the following problems occurred, can you help me solve it? 
Traceback (most recent call last):
  File "F:/brushstroke-parameterized-style-transfer-master/brushstroke-parameterized-style-transfer-master/main.py", line 11, in <module>
    from param_stroke import BrushStrokeRenderer
  File "F:\brushstroke-parameterized-style-transfer-master\brushstroke-parameterized-style-transfer-master\param_stroke.py", line 3, in <module>
    from torch_cluster import knn
  File "F:\brushstroke-parameterized-style-transfer-master\brushstroke-parameterized-style-transfer-master\torch_cluster\__init__.py", line 14, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'

Process finished with exit code 1

**Comment by justanhduc** [comment]
Hi @Max-Well-Wang. You didn't install torch_cluster successfully, so the library finding returns `None`. Are you using Windows? Have you tried installing torch_cluster from the provided wheel in that repo? If you have any trouble installing it, you can ask in the torch_cluster repo directly.

**Comment by Max-Well-Wang** [comment]
The problem has been solved, thank you very much
